class Config:
    # ...existing code...
    SECRET_KEY = 'harsh69archit420vedashree0pranay80082'  # Secret key for Flask app
    FIREBASE_SERVICE_ACCOUNT_KEY = 'D:/wewin/NGO_Lite/credentials/foodhub-767ec-firebase-adminsdk-fbsvc-e65bca27f6.json'  # Use forward slashes
    # ...existing code...
